version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    environment:
      - DB_HOST=db
      - DB_USERNAME=jdoe
      - DB_DATABASE=application
      - DB_PASSWORD=secret
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - .:/srv/app

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=jdoe
      - MYSQL_DATABASE=application
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - db
    ports:
        - 8000:80
    environment:
      - MYSQL_USER=jdoe
      - MYSQL_PASSWORD=secret

volumes:
  db_data: